// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAn6cCBGAN2BE5W9zwfqW7xurgVnGce4',
    appId: '1:248182575361:web:63c9f5fc16d084e19d4b00',
    messagingSenderId: '248182575361',
    projectId: 'mynotesflutterappmadebyabdu',
    authDomain: 'mynotesflutterappmadebyabdu.firebaseapp.com',
    storageBucket: 'mynotesflutterappmadebyabdu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqm29NZEX8CBNs2RtquObXn0SYYp_iZtE',
    appId: '1:248182575361:android:14561c96457c44a49d4b00',
    messagingSenderId: '248182575361',
    projectId: 'mynotesflutterappmadebyabdu',
    storageBucket: 'mynotesflutterappmadebyabdu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-L4PTE1-BiVBg4KyB7SJOaHtj3WchvI',
    appId: '1:248182575361:ios:0cac6d7f4b8b28a09d4b00',
    messagingSenderId: '248182575361',
    projectId: 'mynotesflutterappmadebyabdu',
    storageBucket: 'mynotesflutterappmadebyabdu.appspot.com',
    iosClientId: '248182575361-ot6eubc2qj7icvkr6961g4ld87vb1c4j.apps.googleusercontent.com',
    iosBundleId: 'com.thisisthepage.mynotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-L4PTE1-BiVBg4KyB7SJOaHtj3WchvI',
    appId: '1:248182575361:ios:0cac6d7f4b8b28a09d4b00',
    messagingSenderId: '248182575361',
    projectId: 'mynotesflutterappmadebyabdu',
    storageBucket: 'mynotesflutterappmadebyabdu.appspot.com',
    iosClientId: '248182575361-ot6eubc2qj7icvkr6961g4ld87vb1c4j.apps.googleusercontent.com',
    iosBundleId: 'com.thisisthepage.mynotesapp',
  );
}
